export const siteConfig = {
  name: "Setups Works",
  shortName: "Setups Works",
  tagline: "The Digital Agency.",
  description:
    "Setups Works is a premium digital agency crafting high-performance websites, web & mobile apps, AI products, and brand experiences that move businesses forward.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000",
  email: "info@setups.works",
  phone: "+91 6383984698",
  location: "Chennai, Tamil Nadu, India",
  foundingDate: "2020",
  priceRange: "$$",
  address: {
    locality: "Chennai",
    region: "Tamil Nadu",
    postalCode: "600001",
    country: "IN",
  },
  geo: { lat: 13.0826802, lng: 80.2707184 },
  googleBusiness: "https://share.google/ZwR52us1CGd82FHW6",
  wikidata: "https://www.wikidata.org/wiki/Q140500419",
  areaServed: ["Chennai", "Tamil Nadu", "India", "Worldwide"],
  founderProfile: {
    name: "Nitheesh Rajendran",
    jobTitle: "Founder",
    description:
      "Founder of Setups Works. Passionate about Artificial Intelligence, software engineering, and building developer tools that help programmers prepare for coding interviews.",
    knowsAbout: [
      "Artificial Intelligence",
      "Software Engineering",
      "Competitive Programming",
      "Data Structures and Algorithms",
      "Technical Interview Preparation",
      "Frontend Development",
      "React",
      "Next.js",
      "TypeScript",
      "Machine Learning",
      "Web Development",
    ],
    sameAs: [
      "https://www.linkedin.com/in/nitheeshdr/",
      "https://github.com/nitheeshdr",
      "https://www.imdb.com/name/nm16304237/",
      "https://www.youtube.com/@nitheeshrajendran",
      "https://www.wikidata.org/wiki/Q140500455",
    ],
  },
  ogImage: "/opengraph-image",
  links: {
    twitter: "https://x.com/setupsworks",
    github: "https://github.com/nitheeshdr",
    linkedin: "https://linkedin.com/company/setups-works",
    dribbble: "",
    instagram: "https://instagram.com/setups.works",
  },
  keywords: [
    "digital agency",
    "web development",
    "react development",
    "next.js agency",
    "MERN stack",
    "UI UX design",
    "mobile app development",
    "AI development",
    "SEO",
    "branding",
  ],
} as const;

export type SiteConfig = typeof siteConfig;
